backend:
  name: git-gateway
  branch: main

media_folder: "assets/img" # Onde as fotos do celular vão cair
public_folder: "/assets/img"

collections:
  - name: "servicos"
    label: "Nossos Serviços"
    folder: "galeria" # Ele vai criar uma pasta 'galeria' para organizar
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título do Serviço", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Foto do Trabalho", name: "featuredImage", widget: "image"}
      - {label: "Descrição Curta", name: "body", widget: "markdown"}
