backend:
  name: github
  repo: eduardo345game/BobEletrica # EXEMPLO: eduardo345game/BobEletrica
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "servicos"
    label: "Nossos Serviços"
    label_singular: "Serviço"
    folder: "galeria"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título do Trabalho", name: "title", widget: "string"}
      - {label: "Data do Serviço", name: "date", widget: "datetime"}
      - {label: "Foto da Obra", name: "featuredImage", widget: "image"}
      - {label: "Descrição", name: "body", widget: "markdown"}
